apiVersion: apps/v1
kind: Deployment
metadata:
  name: legacy-c-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: legacy-c-app
  template:
    metadata:
      labels:
        app: legacy-c-app
    spec:
      containers:
      - name: legacy-c-app
        image: mukundbabbar/legacy-c-app:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8087

---
apiVersion: v1
kind: Service
metadata:
  name: legacy-c-app
spec:
  selector:
    app: legacy-c-app
  ports:
  - name: "8080"
    port: 8087
    targetPort: 8087
status:
  loadBalancer: {}
