apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
spec:
  selector:
    matchLabels:
      name: login
  replicas: 1
  template:
    metadata:
      labels:
        name: login
    spec:
      containers:
        - name: login
          image: mukundbabbar/java-apps:1.1
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
          env:
            - name: SPLUNK_OTEL_AGENT
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_SERVICE_NAME
              value: login
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://$(SPLUNK_OTEL_AGENT):4318"
            - name: SPLUNK_OPAMP_ENABLED
              value: "true"
            - name: SPLUNK_OPAMP_ENDPOINT
              value: "http://$(SPLUNK_OTEL_AGENT):4320/v1/opamp"
          envFrom:
          - configMapRef:
              name: agent-config
          volumeMounts:
          - mountPath: /tmp/agent/
            name: splunk-otel-java
      initContainers:
      - name: splunk-otel-init
        image: busybox
        command: ["/bin/sh","-c"]
        args: ["wget https://github.com/signalfx/splunk-otel-java/releases/latest/download/splunk-otel-javaagent.jar -O /tmp/splunk-otel-javaagent.jar"]
        volumeMounts:
        - mountPath: /tmp
          name: splunk-otel-java
      volumes:
      - emptyDir: {}
        name: splunk-otel-java

---
apiVersion: v1
kind: Service
metadata:
  name: login
spec:
  selector:
    name: login
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
status:
  loadBalancer: {}
