apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loan-frontend
  template:
    metadata:
      labels:
        app: loan-frontend
    spec:
      containers:
        - name: loan-frontend
          image: mukundbabbar/banking-demo-ui:latest
          ports:
            - containerPort: 81
          envFrom:
            - configMapRef:
                name: agent-config
          env:
            - name: APPD_JS_SNIPPET
              valueFrom:
                secretKeyRef:
                  name: appd-snippet
                  key: snippet.js
          volumeMounts:
            - name: appd-snippet-volume
              mountPath: /app/config/snippet.js
              subPath: snippet.js
      volumes:
        - name: appd-snippet-volume
          secret:
            secretName: appd-snippet
---
apiVersion: v1
kind: Service
metadata:
  name: loan-frontend-service
spec:
  selector:
    app: loan-frontend
  ports:
    - protocol: TCP
      port: 81
      targetPort: 81

